### ISSUE TITLE
Remove change-case?

### ISSUE THREAD

**Issue by harveysanders** [OperationSpark/opspark#76]
TODO: Remove elsewhere and uninstall dependency

_Originally posted by @ptbarnum4 in https://github.com/OperationSpark/opspark/pull/73#discussion_r1470362427_

**Comment by ptbarnum4** [comment]
@harveysanders when saying that, I thought this module was unmaintained and we should just use lodash instead. Looking it up, it is still [actively maintained](https://www.npmjs.com/package/change-case). We can close this issue
